export enum RepositoryEnum  {
    PRODUCT_REPOSITORY = "PROCUCT_REPOSITORY",
    CATEGORY_REPOSITORY = " CATEGORY_REPOSITORY",
    PERSONA_REPOSITORY = "PERSONA_REPOSITORY",
    FUNDACION_REPOSITORY = "FUNDACION_REPOSITORY"
}